name: ripple_car_frontend
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  validators: ^3.0.0
  get_storage: ^2.0.3
  url_launcher: ^6.1.5
  simple_animations: ^5.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/layout/
    - assets/images/icons/
    - assets/images/cars/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: HighSpeed
      fonts:
        - asset: assets/fonts/HighSpeed-Regular.otf

    - family: Dosis
      fonts:
        - asset: assets/fonts/Dosis-Regular.ttf       